#pragma once

#include "MessageIn.hpp"

enum ParseStatus {
    VALID_MSG,
	PERR_MSG_LENGTH,
	PERR_NO_CRLF,
	PERR_NO_SPACE_AFTER_PREFIX,
	PERR_PREFIX_LENGTH,
	PERR_PREFIX_MISSING_NICK,
	PERR_PREFIX_MISSING_USER,
	PERR_PREFIX_MISSING_HOST,
	PERR_PREFIX_INVALID_NICK,
	PERR_PREFIX_INVALID_USER,
	PERR_PREFIX_INVALID_HOST,
	PERR_PREFIX_INVALID_SERVERNAME,
	PERR_MISSING_COMMAND,
	PERR_INVALID_COMMAND,
	PERR_NUMERIC_COMMAND_TOO_LONG,
	PERR_INVALID_CHARACTERS,
	PERR_EMPTY_SPACE,
	PERR_EXCEED_15_PARAM,
	PERR_NONE // must always be the last one
};

extern const std::string g_parseErrors[PERR_NONE];

MessageIn   parseMessage(msgTokens tokens, ParseStatus &status);